# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-03 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20160903_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='currency_final',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_krw',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_opposite',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='currency',
            name='opposite_nation',
            field=models.CharField(max_length=3),
        ),
    ]
