# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-03 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20160903_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyEUR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_krw', models.FloatField(default=0)),
                ('currency_opposite', models.FloatField(default=0)),
                ('currency_final', models.FloatField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='published date')),
            ],
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
