# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-03 10:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20160903_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyCNY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=3)),
                ('currency_rate', models.FloatField(default=0)),
                ('currency_final', models.FloatField(default=0)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='published date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyGBP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=3)),
                ('currency_rate', models.FloatField(default=0)),
                ('currency_final', models.FloatField(default=0)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='published date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyJPY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=3)),
                ('currency_rate', models.FloatField(default=0)),
                ('currency_final', models.FloatField(default=0)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='published date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyKRW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=3)),
                ('currency_rate', models.FloatField(default=0)),
                ('currency_final', models.FloatField(default=0)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='published date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='currencyeur',
            old_name='currency_krw',
            new_name='currency_rate',
        ),
        migrations.RemoveField(
            model_name='currencyeur',
            name='currency_opposite',
        ),
        migrations.AddField(
            model_name='currencyeur',
            name='nation',
            field=models.CharField(default=datetime.datetime(2016, 9, 3, 10, 40, 6, 478354, tzinfo=utc), max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currencyeur',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='published date'),
        ),
    ]
