# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_auto_20160903_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencycny',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='currencyeur',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='currencygbp',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='currencyjpy',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='currencykrw',
            name='pub_date',
        ),
    ]
