# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 16:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_auto_20160906_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencycny',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2016, 9, 8), verbose_name='published date'),
        ),
        migrations.AddField(
            model_name='currencyeur',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2016, 9, 8), verbose_name='published date'),
        ),
        migrations.AddField(
            model_name='currencygbp',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2016, 9, 8), verbose_name='published date'),
        ),
        migrations.AddField(
            model_name='currencyjpy',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2016, 9, 8), verbose_name='published date'),
        ),
        migrations.AddField(
            model_name='currencykrw',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2016, 9, 8), verbose_name='published date'),
        ),
    ]
