# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_auto_20160908_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencycny',
            name='pub_date',
            field=models.DateTimeField(verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='currencyeur',
            name='pub_date',
            field=models.DateTimeField(verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='currencygbp',
            name='pub_date',
            field=models.DateTimeField(verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='currencyjpy',
            name='pub_date',
            field=models.DateTimeField(verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='currencykrw',
            name='pub_date',
            field=models.DateTimeField(verbose_name='published date'),
        ),
    ]
