# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_auto_20160908_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencycny',
            name='nation',
            field=models.CharField(default='CNY', max_length=3),
        ),
        migrations.AlterField(
            model_name='currencyeur',
            name='nation',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='currencygbp',
            name='nation',
            field=models.CharField(default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='currencyjpy',
            name='nation',
            field=models.CharField(default='JPY', max_length=3),
        ),
        migrations.AlterField(
            model_name='currencykrw',
            name='nation',
            field=models.CharField(default='KRW', max_length=3),
        ),
    ]
