# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_auto_20160908_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencycny',
            name='nation',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='currencyeur',
            name='nation',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='currencygbp',
            name='nation',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='currencyjpy',
            name='nation',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='currencykrw',
            name='nation',
            field=models.CharField(max_length=3),
        ),
    ]
