# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 15:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0014_auto_20160920_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencycny',
            name='title',
            field=models.CharField(default='\uc704\uc548\ud654', max_length=3),
        ),
        migrations.AddField(
            model_name='currencyeur',
            name='title',
            field=models.CharField(default='\uc720\ub85c\ud654', max_length=3),
        ),
        migrations.AddField(
            model_name='currencygbp',
            name='title',
            field=models.CharField(default='\ud30c\uc6b4\ub4dc', max_length=3),
        ),
        migrations.AddField(
            model_name='currencyjpy',
            name='title',
            field=models.CharField(default='\uc5d4\ud654', max_length=3),
        ),
        migrations.AddField(
            model_name='currencykrw',
            name='title',
            field=models.CharField(default='\ud55c\uad6d\ub3c8', max_length=3),
        ),
        migrations.AlterField(
            model_name='currencycny',
            name='pub_date',
            field=models.DateField(default=datetime.date(2016, 9, 27), verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='currencyeur',
            name='pub_date',
            field=models.DateField(default=datetime.date(2016, 9, 27), verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='currencygbp',
            name='pub_date',
            field=models.DateField(default=datetime.date(2016, 9, 27), verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='currencyjpy',
            name='pub_date',
            field=models.DateField(default=datetime.date(2016, 9, 27), verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='currencykrw',
            name='pub_date',
            field=models.DateField(default=datetime.date(2016, 9, 27), verbose_name='published date'),
        ),
    ]
