# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 09:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0015_auto_20160927_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencycny',
            name='pub_date',
            field=models.DateField(default=datetime.date(2016, 10, 3), verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='currencyeur',
            name='pub_date',
            field=models.DateField(default=datetime.date(2016, 10, 3), verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='currencygbp',
            name='pub_date',
            field=models.DateField(default=datetime.date(2016, 10, 3), verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='currencyjpy',
            name='pub_date',
            field=models.DateField(default=datetime.date(2016, 10, 3), verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='currencykrw',
            name='pub_date',
            field=models.DateField(default=datetime.date(2016, 10, 3), verbose_name='published date'),
        ),
    ]
